.gitignore, README.md, build.gradle, src/main/java/challenging/application/auth/annotation/LoginMember.java, src/main/java/challenging/application/auth/configuration/SecurityConfiguration.java, src/main/java/challenging/application/auth/configuration/WebConfig.java, src/main/java/challenging/application/auth/controller/ReissueController.java, src/main/java/challenging/application/auth/domain/Member.java, src/main/java/challenging/application/auth/domain/RefreshToken.java, src/main/java/challenging/application/auth/exception/ErrorResult.java, src/main/java/challenging/application/auth/exception/exceptionMessage/ExceptionMessage.java, src/main/java/challenging/application/auth/filter/JWTAccessFilter.java, src/main/java/challenging/application/auth/filter/JWTLogoutFilter.java, src/main/java/challenging/application/auth/filter/JWTRefreshFilter.java, src/main/java/challenging/application/auth/jwt/JWTUtils.java, src/main/java/challenging/application/auth/oauth/OAuth2SuccessHandler.java, src/main/java/challenging/application/auth/oauth/OAuth2UserImpl.java, src/main/java/challenging/application/auth/oauth/OAuth2UserServiceImpl.java, src/main/java/challenging/application/auth/oauth/oauthResponse/NaverResponse.java, src/main/java/challenging/application/auth/oauth/oauthResponse/OAuth2Response.java, src/main/java/challenging/application/auth/repository/MemberRepository.java, src/main/java/challenging/application/auth/repository/RefreshTokenRepository.java, src/main/java/challenging/application/auth/resolver/CustomAuthenticationPrincipalArgumentResolver.java, src/main/java/challenging/application/auth/servletUtils/cookie/CookieUtils.java, src/main/java/challenging/application/auth/servletUtils/jwtUtils/JWTResponseUtils.java, src/main/java/challenging/application/controller/AuthController.java, src/main/java/challenging/application/controller/MainController.java, src/main/java/challenging/application/controller/MyController.java, src/main/resources/application.properties, src/main/resources/templates/loginForm.html
=> Week3 Develop 최종 Main PR

src/main/java/challenging/application/controller/ChallengeController.java, src/main/java/challenging/application/domain/Challenge.java, src/main/java/challenging/application/dto/response/ChallengeResponseDTO.java, src/main/java/challenging/application/exception/ErrorResponse.java, src/main/java/challenging/application/exeption/GlobalExceptionHandler.java, src/main/java/challenging/application/exeption/challenge/ChallengeNotFoundException.java, src/main/java/challenging/application/exeption/challenge/InvalidDateException.java, src/main/java/challenging/application/repository/ChallengeRepository.java, src/main/java/challenging/application/service/ChallengeService.java, src/main/java/challenging/application/util/ResponseUtil.java
1. 챌린지 엔티티 추가
- 피그마를 보고 host_id가 필요하다 느껴서 ERD와 API 문서에 추가함
- 시간이 나면 챌린지 참가자 관련 entity를 만들 예정
2.  단건 조회 API 구현
나중에 테스트 코드 추가 예정
수정 사항 알려주시면 감사하겠습니다!
=> [WEEK4 24 BE] 이가현 WEEK4 개발 PR - 1

src/main/java/challenging/application/controller/ChallengeController.java, src/main/java/challenging/application/domain/Category.java, src/main/java/challenging/application/domain/Challenge.java, src/main/java/challenging/application/domain/Participant.java, src/main/java/challenging/application/dto/request/ChallengeRequestDTO.java, src/main/java/challenging/application/dto/response/ChallengeResponseDTO.java, src/main/java/challenging/application/exception/GlobalExceptionHandler.java, src/main/java/challenging/application/exception/challenge/CategoryNotFoundException.java, src/main/java/challenging/application/exception/challenge/ChallengeNotFoundException.java, src/main/java/challenging/application/exception/challenge/InvalidDateException.java, src/main/java/challenging/application/exception/challenge/UserNotFoundException.java, src/main/java/challenging/application/repository/CategoryRepository.java, src/main/java/challenging/application/repository/ChallengeRepository.java, src/main/java/challenging/application/repository/ParticipantRepository.java, src/main/java/challenging/application/service/ChallengeService.java
1. 챌린지 카테고리 조회 API
2. 챌린지 생성 API
3. 챌린지 삭제 API
4. 챌린지 예약 API
5. category 엔티티 생성
- 참가자 테이블을 추가하고 관련 로직을 수정했습니다.
- date 관련 로직도 수정했습니다.
수정 사항이나 예외 처리를 더 했으면 좋겠는 점이 있으면 알려주세요!
=> [WEEK5 24 BE] 이가현 WEEK5 개발 PR

readme/README-JANG_JIN_YOUNG.md, src/main/java/challenging/application/auth/controller/AuthController.java, src/main/java/challenging/application/auth/utils/servletUtils/jwtUtils/JWTResponseUtils.java, src/main/java/challenging/application/challenge/controller/ChallengeController.java, src/main/java/challenging/application/challenge/domain/Challenge.java, src/main/java/challenging/application/challenge/repository/ChallengeRepository.java, src/main/java/challenging/application/challenge/service/ChallengeService.java, src/main/java/challenging/application/domain/Category.java, src/main/java/challenging/application/domain/Participant.java, src/main/java/challenging/application/dto/request/DateRequest.java, src/main/java/challenging/application/dto/response/ChallengeResponseDTO.java, src/main/java/challenging/application/dto/response/ReserveChallengeResponse.java, src/main/java/challenging/application/dto/response/UserProfileResponseDTO.java, src/main/java/challenging/application/exception/ErrorResult.java, src/main/java/challenging/application/exception/ExceptionMessage.java, src/main/java/challenging/application/exception/GlobalExceptionHandler.java, src/main/java/challenging/application/exception/challenge/ChallengeNotFoundException.java, src/main/java/challenging/application/userprofile/controller/UserProfileController.java, src/main/java/challenging/application/userprofile/domain/UserProfile.java, src/main/java/challenging/application/userprofile/repository/UserProfileRepository.java, src/main/java/challenging/application/userprofile/service/UserProfileService.java, src/main/java/challenging/application/userprofile/service/UserProfileServiceImpl.java, src/test/java/challenging/application/UserProfileControllerTest.java, src/test/java/challenging/application/UserProfileRepositoryTest.java, src/test/java/challenging/application/UserProfileServiceImplTest.java
팀원들 코드 리팩토링을 했습니다. 또한 제가 생각했을때 필요한 수정사항을 정리해보았습니다.
https://www.notion.so/830ec534654b4f2e8b1c6e87ecc51285?pvs=23
참고 해주세요!!
=> [개발 스프린트 3주차] 장진영

src/main/java/challenging/application/challenge/controller/ChallengeController.java, src/main/java/challenging/application/challenge/service/ChallengeService.java, src/test/java/challenging/application/challenge/ChallengeServiceTest.java
=> [개발 스프린트 8주차] 이가현

src/main/java/challenging/application/challenge/service/ChallengeService.java, src/main/java/challenging/application/dto/response/ChallengeCreateResponse.java, src/main/java/challenging/application/dto/response/ChallengeResponse.java, src/main/java/challenging/application/images/S3PresignedImageService.java, src/main/java/challenging/application/userprofile/service/UserProfileService.java, src/test/java/challenging/application/UserProfileControllerTest.java, src/test/java/challenging/application/UserProfileServiceTest.java, src/test/java/challenging/application/challenge/ChallengeServiceTest.java
유저프로필 챌린지에 presigned 로직 적용시켰습니다.
=> [개발 스프린트 3] 박정우

src/main/java/challenging/application/domain/challenge/controller/ChallengeController.java, src/main/java/challenging/application/domain/challenge/service/ChallengeService.java, src/test/java/challenging/application/challenge/ChallengeRepositoryTest.java
=> [개발 스프린트3] 이가현

src/main/java/challenging/application/domain/challenge/controller/ChallengeController.java, src/main/java/challenging/application/domain/challenge/entity/Challenge.java, src/main/java/challenging/application/domain/challenge/repository/ChallengeRepository.java, src/main/java/challenging/application/domain/challenge/service/ChallengeService.java, src/main/java/challenging/application/global/dto/response/ChallengeResponse.java, src/main/java/challenging/application/global/images/ImageController.java, src/main/java/challenging/application/global/images/ImageService.java
userprofile 부분 postman 테스트 put get 전부 성공했고 s3이미지 올리는 로직은 테스트 성공했습니다.
=> [개발 스프린트3] 박정우

src/main/java/challenging/application/domain/challenge/service/ChallengeService.java, src/main/java/challenging/application/domain/userprofile/controller/UserProfileController.java, src/main/java/challenging/application/domain/userprofile/domain/UserProfile.java, src/main/java/challenging/application/domain/userprofile/service/UserProfileService.java, src/main/java/challenging/application/global/dto/request/UserProfileRequest.java, src/main/java/challenging/application/global/dto/response/chalenge/ChallengeGetResponse.java, src/main/java/challenging/application/global/dto/response/chalenge/ChallengeReservationResponse.java, src/main/java/challenging/application/global/dto/response/userprofile/UserProfileGetResponse.java, src/main/java/challenging/application/global/security/oauth/OAuth2SuccessHandler.java
로그인시 uuid 발급 로직 추가, 모든로직 userId 대신 uuid 반환로직으로 변경 , image 로직 presigned에서 multpart로 로직 수정
=> [개발 스프린트4] 박정우

src/main/java/challenging/application/domain/auth/entity/Member.java, src/main/java/challenging/application/domain/challenge/controller/ChallengeController.java, src/main/java/challenging/application/domain/challenge/repository/ChallengeRepository.java, src/main/java/challenging/application/domain/challenge/service/ChallengeService.java, src/main/java/challenging/application/domain/participant/repository/ParticipantRepository.java, src/main/java/challenging/application/domain/userprofile/domain/UserProfile.java, src/main/java/challenging/application/global/dto/request/ChallengeVoteRequest.java
=> [스프린트 4]박정우

src/main/java/challenging/application/domain/challenge/controller/ChallengeController.java, src/main/java/challenging/application/domain/challenge/service/ChallengeService.java, src/main/java/challenging/application/domain/participant/repository/ParticipantRepository.java, src/main/java/challenging/application/global/dto/response/chalenge/ChallengeCancelResponse.java
개발내용
- 챌린지 취소 추가
- 챌린지 삭제 로직 수정
=> [개발 스프린트4] 장진영 - 11주차(3)

src/test/java/challenging/application/domain/userprofile/service/UserProfileServiceTest.java, src/test/java/challenging/application/global/images/ImageServiceTest.java
로직변경에 따른 유저 프로필 테스트코드 변경 이미지 path static으로 분리
=> [스프린트 4] 박정우 11주차(4)

src/main/java/challenging/application/domain/challenge/controller/ChallengeController.java, src/main/java/challenging/application/domain/userprofile/controller/UserProfileController.java, src/main/java/challenging/application/domain/userprofile/service/UserProfileService.java, src/main/java/challenging/application/global/dto/request/ChallengeRequest.java, src/main/java/challenging/application/global/dto/response/chalenge/ChallengeCancelResponse.java, src/main/java/challenging/application/global/dto/response/userprofile/HostProfileGetResponse.java, src/test/java/challenging/application/domain/challenge/controller/ChallengeControllerTest.java, src/test/java/challenging/application/domain/userprofile/controller/UserProfileControllerTest.java, src/test/java/challenging/application/domain/userprofile/service/UserProfileServiceTest.java, src/test/java/challenging/application/global/images/ImageServiceTest.java
개발 내용
- ChallengeController Test 추가
- UserProfile 호스트 프로필 Test 추가
=> [개발 스프린트4] 장진영 - 11주차(5)

src/main/java/challenging/application/global/error/ErrorCode.java, src/main/java/challenging/application/global/error/images/ImageFileDeleteException.java, src/main/java/challenging/application/global/error/images/ImageFileNotFoundException.java, src/main/java/challenging/application/global/error/images/ImageFileUploadException.java, src/main/java/challenging/application/global/error/images/S3Exception.java, src/main/java/challenging/application/global/images/ImageService.java, src/test/java/challenging/application/global/images/ImageServiceTest.java
=> [스프린트 4] 박정우 11주차(5)

.gitignore, build.gradle, src/main/java/challenging/application/domain/participant/entity/Participant.java, src/main/java/challenging/application/global/security/configuration/SecurityConfiguration.java, src/main/resources/application.properties, src/test/java/challenging/application/domain/challenge/repository/ChallengeRepositoryTest.java, src/test/resources/application.properties
개발내용
- db 분리
- mysql 적용
- 테스트 db : h2
=> [개발 스프린트4] 장진영 - 11주차(6)

src/main/java/challenging/application/domain/challenge/entity/Challenge.java, src/main/java/challenging/application/domain/challenge/service/ChallengeService.java, src/main/java/challenging/application/global/dto/request/ChallengeRequest.java, src/main/java/challenging/application/global/dto/response/chalenge/ChallengeCreateResponse.java, src/main/java/challenging/application/global/dto/response/chalenge/ChallengeGetResponse.java, src/main/java/challenging/application/global/dto/response/chalenge/ChallengeReservationResponse.java, src/test/java/challenging/application/domain/challenge/controller/ChallengeControllerTest.java, src/test/java/challenging/application/domain/challenge/service/ChallengeServiceTest.java
=> [개발 스프린트4] 장진영 - 11주차(7)

src/main/java/challenging/application/domain/challenge/controller/ChallengeController.java, src/main/java/challenging/application/global/dto/response/ApiResponse.java, src/main/java/challenging/application/global/error/GlobalExceptionHandler.java
개발 내용
- 이미지 validation 기능 추가
- 이미지 validation handler 추가
=> [개발 스프린트4] 장진영 - 11주차(8)

src/main/java/challenging/application/domain/challenge/entity/Challenge.java
=> [개발 스프린트4] 장진영 - 11주차(9)

src/main/java/challenging/application/domain/challenge/service/ChallengeService.java, src/main/java/challenging/application/global/error/ErrorCode.java, src/main/java/challenging/application/global/error/user/ForbiddenException.java
=> [개발 스프린트4] 장진영 - 11주차(10)

src/main/java/challenging/application/domain/challenge/service/ChallengeService.java, src/main/java/challenging/application/global/error/ErrorCode.java, src/main/java/challenging/application/global/error/challenge/ParticipantNotFoundException.java
=> [스프린트 4] 박정우 11주차(6)
